AWSTemplateFormatVersion: "2010-09-09"
Resources:
  VPC2:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: "true"
      EnableDnsHostnames: "true"
      InstanceTenancy: default
      Tags: 
        - Key: Name
          Value: "test2-vpc"

  public-subnet-1a:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref VPC2
    CidrBlock: 10.0.0.0/24
    AvailabilityZone: "ap-northeast-1a"
    Tags:
    - Key: stack
      Value: production

  InternetGateway:
    Type: "AWS::EC2::InternetGateway"
    Properties:
      Tags:
        - Key: Name
          Value: "test2-igw"

  InternetGatewayAttachment:
    Type: "AWS::EC2::VPCGatewayAttachment"
    Properties:
      InternetGatewayId: !Ref InternetGateway
      VpcId: !Ref VPC2

