AWSTemplateFormatVersion: "2010-09-09"
Resources:
  EC2SG:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: ec2-sg-cf
      GroupDescription: Allow SSH and HTTP access
      VpcId: "vpc-0e3e5318a67c26be2"
      SecurityGroupIngress:
        # http
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        # ssh
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0

  EC2: 
    Type: AWS::EC2::Instance
    Properties: 
      ImageId: ami-06098fd00463352b6 
      KeyName: "AWS::EC2::KeyPair::KeyName"
      InstanceType: t2.micro
      NetworkInterfaces: 
        - AssociatePublicIpAddress: "true"
          DeviceIndex: "0"
          SubnetId: "subnet-06a8e44aa15e0055b"
          GroupSet:
            - !Ref EC2SG
      Tags:
          - Key: Name
            Value: ec2-test2
