AWSTemplateFormatVersion: "2010-09-09"
Resources:
  ElasticIP1:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

Outputs:
  EIPOutput1:
    Value: !Ref ElasticIP1
    Export:
      Name: "EIP1"
